default: &default
  # Database configuration
  DB_PORT: "3306"
  DB_POOL: <%= ENV.fetch("RAILS_MAX_THREADS") { "5" } %>
  DB_HOST: "<db_host>"
  DB_DATABASE: "<db_name>"
  DB_USERNAME: "<db_username>"
  DB_PASSWORD: "<db_password>"

development:
  <<: *default

integration:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
