# MySQL config
# git update-index --assume-unchanged database.yml to not ignore changes
# git update-index --no-assume-unchanged database.yml to not ignore changes
development:
  adapter: mysql2
  encoding: utf8
  secure_auth: false
  host: <%= '127.0.0.1' %>
  database: <%= 'rspec_tutorial' %>
  username: <%= 'ramon' %>
  password: <%= 'ramon' %>

test: &test
  adapter: mysql2
  encoding: utf8
  host: <%= '127.0.0.1' %>
  database: <%= 'rspec_tutorial' %>
  username: <%= 'ramon' %>
  password: <%= 'ramon' %>
  secure_auth: false
